name: JFrog-GitHub NPM Publish OIDC Integration
on: push
permissions:
  id-token: write
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   # This action checks out the code from the repository
   - name: Checkout
     uses: actions/checkout@v4
   - name: Setup JFrog CLI
     uses: jfrog/setup-jfrog-cli@v4
     env:
          JF_URL: '${{ secrets.JF_URL }}'
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
   - name: Build Docker image
     run: jf docker build -t elinaf.jfrog.io/jordanta-docker-local/github-test/nginx .
   - name: Get image ID
     run: |
          IMAGE_ID=$(docker images elinaf.jfrog.io/jordanta-docker-local/github-test/nginx --format "{{.ID}}" | head -n1)
          echo "Image ID: $IMAGE_ID"
          echo "image_id=$IMAGE_ID" >> $GITHUB_OUTPUT
   - name: Tag Image
     run: jf docker tag $IMAGE_ID elinaf.jfrog.io/jordanta-docker-push-test/nginx:latest
   - name: Push Docker image
     run: jf docker push elinaf.jfrog.io/jordanta-docker-push-test/nginx:latest

