name: JFrog-GitHub NPM Publish OIDC Integration
'on': push
permissions:
  id-token: write
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   # This action checks out the code from the repository
   - name: Checkout
     uses: actions/checkout@v4
   - name: Setup JFrog CLI
     uses: jfrog/setup-jfrog-cli@v4
     env:
          JF_URL: '${{ secrets.JF_URL }}'
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
   - name: Build Docker image
     run: jf docker build -t elinaf.jfrog.io/jordanta-docker-local/github-test .
   - name: Push Docker image
     run: jf docker push elinaf.jfrog.io/jordanta-docker-local/github-test

