name: JFrog-GitHub NPM Publish OIDC Integration
'on': push
permissions:
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OIDC_AUDIENCE: jfrog-github
      OIDC_PROVIDER: jfrog-github
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_URL: '${{ secrets.JF_URL }}'
        with:
          oidc-provider-name: '${{ env.OIDC_PROVIDER }}'
          oidc-audience: '${{ env.OIDC_AUDIENCE }}'
      - name: "Build Docker image\L"
        run: jf docker build -t elinaf.jfrog.io/jordanta-docker-local/github-test .
      - name: Push Docker image
        run": jf docker push elinaf.jfrog.io/jordanta-docker-local/github-test

